import { Ticket } from "@/types/Ticket";

export const data: Ticket[] = [
    {
        ticket_id: 13,
        flight_id: 1,
        ticket_type: "first",
        ticket_amount: 20,
        fare_amount: "200000.00",
        valid_until: "2024-01-27T05:00:00.000Z",
        created_at: "2024-01-26T13:02:48.153Z",
        updated_at: null,
        flight: {
            flight_id: 1,
            departure_id: 38,
            arrival_id: 60,
            airline_id: 15,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "6811",
            iata: "AA6811",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 38,
                airport_id: 38,
                terminal: "3",
                scheduled_time: "2024-01-06T09:00:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 38,
                    airport_name: "Dougherty County",
                    iata_code: "ABY",
                    gmt: "-5",
                    city_name: "Albina",
                    city_iata_code: "ABY",
                    country_iso_code: "US",
                    country_name: "United States",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 60,
                airport_id: 60,
                terminal: "1",
                scheduled_time: "2024-01-06T15:05:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 60,
                    airport_name: "Aden International Airport",
                    iata_code: "ADE",
                    gmt: "3",
                    city_name: "Aguaclara",
                    city_iata_code: "ADE",
                    country_iso_code: "YE",
                    country_name: "Yemen",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 15,
                name: "Iberia",
                iata: "IB",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 12,
        flight_id: 10,
        ticket_type: "first",
        ticket_amount: 50,
        fare_amount: "1500000.00",
        valid_until: "2024-01-30T17:00:00.000Z",
        created_at: "2024-01-24T17:04:22.710Z",
        updated_at: null,
        flight: {
            flight_id: 10,
            departure_id: 62,
            arrival_id: 54,
            airline_id: 77,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "6300",
            iata: "X16300",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 62,
                airport_id: 62,
                terminal: "2",
                scheduled_time: "2024-01-06T08:55:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 62,
                    airport_name: "Lenawee County",
                    iata_code: "ADG",
                    gmt: "-5",
                    city_name: "Acuna",
                    city_iata_code: "ADG",
                    country_iso_code: "US",
                    country_name: "United States",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 54,
                airport_id: 54,
                terminal: "8",
                scheduled_time: "2024-01-06T12:00:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 54,
                    airport_name: "Arcata",
                    iata_code: "ACV",
                    gmt: "-8",
                    city_name: "Acandi",
                    city_iata_code: "ACV",
                    country_iso_code: "US",
                    country_name: "United States",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 77,
                name: "Sichuan Airlines",
                iata: "3U",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 10,
        flight_id: 9,
        ticket_type: "first",
        ticket_amount: 15,
        fare_amount: "1200000.00",
        valid_until: "2024-01-29T17:00:00.000Z",
        created_at: "2024-01-24T17:02:50.031Z",
        updated_at: null,
        flight: {
            flight_id: 9,
            departure_id: 51,
            arrival_id: 78,
            airline_id: 92,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "8387",
            iata: "G58387",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 51,
                airport_id: 51,
                terminal: "8",
                scheduled_time: "2024-01-06T14:55:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 51,
                    airport_name: "Araracuara",
                    iata_code: "ACR",
                    gmt: "-5",
                    city_name: "Acapulco",
                    city_iata_code: "ACR",
                    country_iso_code: "CO",
                    country_name: "Colombia",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 78,
                airport_id: 78,
                terminal: "I",
                scheduled_time: "2024-01-06T14:15:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 78,
                    airport_name: "Abemama Atoll",
                    iata_code: "AEA",
                    gmt: "12",
                    city_name: "Arandis",
                    city_iata_code: "AEA",
                    country_iso_code: "KI",
                    country_name: "Kiribati",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 92,
                name: "Shandong Airlines",
                iata: "SC",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 9,
        flight_id: 8,
        ticket_type: "first",
        ticket_amount: 30,
        fare_amount: "1600000.00",
        valid_until: "2024-01-28T17:00:00.000Z",
        created_at: "2024-01-24T17:02:25.653Z",
        updated_at: null,
        flight: {
            flight_id: 8,
            departure_id: 85,
            arrival_id: 22,
            airline_id: 64,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "2774",
            iata: "ZH2774",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 85,
                airport_id: 85,
                terminal: "8",
                scheduled_time: "2024-01-06T08:30:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 85,
                    airport_name: "Vigra",
                    iata_code: "AES",
                    gmt: "1",
                    city_name: "Kodiak",
                    city_iata_code: "AES",
                    country_iso_code: "NO",
                    country_name: "Norway",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 22,
                airport_id: 22,
                terminal: "2",
                scheduled_time: "2024-01-06T09:05:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 22,
                    airport_name: "Abadan",
                    iata_code: "ABD",
                    gmt: "3.30",
                    city_name: "Araxa",
                    city_iata_code: "ABD",
                    country_iso_code: "IR",
                    country_name: "Iran",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 64,
                name: "Xiamen Airlines",
                iata: "MF",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 8,
        flight_id: 7,
        ticket_type: "first",
        ticket_amount: 20,
        fare_amount: "2300000.00",
        valid_until: "2024-01-31T07:00:00.000Z",
        created_at: "2024-01-24T17:01:17.914Z",
        updated_at: null,
        flight: {
            flight_id: 7,
            departure_id: 6,
            arrival_id: 93,
            airline_id: 76,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "5268",
            iata: "HO5268",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 6,
                airport_id: 6,
                terminal: "8",
                scheduled_time: "2024-01-06T10:50:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 6,
                    airport_name: "Arapoti",
                    iata_code: "AAG",
                    gmt: "-3",
                    city_name: "Arapoti",
                    city_iata_code: "AAG",
                    country_iso_code: "BR",
                    country_name: "Brazil",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 93,
                airport_id: 93,
                terminal: "2",
                scheduled_time: "2024-01-06T20:15:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 93,
                    airport_name: "Amalfi",
                    iata_code: "AFI",
                    gmt: "-5",
                    city_name: "Abemama Atoll",
                    city_iata_code: "AFI",
                    country_iso_code: "CO",
                    country_name: "Colombia",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 76,
                name: "ANA",
                iata: "NH",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 6,
        flight_id: 5,
        ticket_type: "first",
        ticket_amount: 40,
        fare_amount: "4000000.00",
        valid_until: "2024-01-31T17:00:00.000Z",
        created_at: "2024-01-24T16:46:22.413Z",
        updated_at: null,
        flight: {
            flight_id: 5,
            departure_id: 98,
            arrival_id: 70,
            airline_id: 93,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "8353",
            iata: "QF8353",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 98,
                airport_id: 98,
                terminal: "A",
                scheduled_time: "2024-01-06T04:30:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 98,
                    airport_name: "Afutara Aerodrome",
                    iata_code: "AFT",
                    gmt: "11",
                    city_name: "Abeche",
                    city_iata_code: "AFT",
                    country_iso_code: "SB",
                    country_name: "Solomon Islands",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 70,
                airport_id: 70,
                terminal: "2",
                scheduled_time: "2024-01-06T11:35:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 70,
                    airport_name: "Kodiak Airport",
                    iata_code: "ADQ",
                    gmt: "-9",
                    city_name: "Zabol",
                    city_iata_code: "ADQ",
                    country_iso_code: "US",
                    country_name: "United States",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 93,
                name: "China Eastern Airlines",
                iata: "MU",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 5,
        flight_id: 4,
        ticket_type: "first",
        ticket_amount: 10,
        fare_amount: "1000000.00",
        valid_until: "2024-01-28T17:00:00.000Z",
        created_at: "2024-01-24T16:45:34.623Z",
        updated_at: null,
        flight: {
            flight_id: 4,
            departure_id: 14,
            arrival_id: 46,
            airline_id: 87,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "8700",
            iata: "G58700",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 14,
                airport_id: 14,
                terminal: "1",
                scheduled_time: "2024-01-06T07:50:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 14,
                    airport_name: "Aarhus Airport",
                    iata_code: "AAR",
                    gmt: "1",
                    city_name: "Anaco",
                    city_iata_code: "AAR",
                    country_iso_code: "DK",
                    country_name: "Denmark",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 46,
                airport_id: 46,
                terminal: "4",
                scheduled_time: "2024-01-06T16:25:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 46,
                    airport_name: "The Blaye",
                    iata_code: "ACI",
                    gmt: "6",
                    city_name: "Abuja",
                    city_iata_code: "ACI",
                    country_iso_code: "GG",
                    country_name: "Guernsey",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 87,
                name: "Sichuan Airlines",
                iata: "3U",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 4,
        flight_id: 3,
        ticket_type: "first",
        ticket_amount: 30,
        fare_amount: "1550000.00",
        valid_until: "2024-01-26T10:35:00.000Z",
        created_at: "2024-01-24T16:44:59.848Z",
        updated_at: null,
        flight: {
            flight_id: 3,
            departure_id: 70,
            arrival_id: 45,
            airline_id: 90,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "163",
            iata: "BC163",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 70,
                airport_id: 70,
                terminal: "2",
                scheduled_time: "2024-01-06T08:45:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 70,
                    airport_name: "Kodiak Airport",
                    iata_code: "ADQ",
                    gmt: "-9",
                    city_name: "Zabol",
                    city_iata_code: "ADQ",
                    country_iso_code: "US",
                    country_name: "United States",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 45,
                airport_id: 45,
                terminal: "3",
                scheduled_time: "2024-01-06T16:30:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 45,
                    airport_name: "Altenrhein",
                    iata_code: "ACH",
                    gmt: "1",
                    city_name: "Atambua",
                    city_iata_code: "ACH",
                    country_iso_code: "CH",
                    country_name: "Switzerland",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 90,
                name: "Loong Air",
                iata: "GJ",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 3,
        flight_id: 2,
        ticket_type: "first",
        ticket_amount: 50,
        fare_amount: "2000000.00",
        valid_until: "2024-01-29T05:00:00.000Z",
        created_at: "2024-01-24T16:43:46.429Z",
        updated_at: null,
        flight: {
            flight_id: 2,
            departure_id: 58,
            arrival_id: 42,
            airline_id: 75,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "4248",
            iata: "QR4248",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 58,
                airport_id: 58,
                terminal: "1",
                scheduled_time: "2024-01-06T14:05:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 58,
                    airport_name: "Adnan Menderes Airport",
                    iata_code: "ADB",
                    gmt: "3",
                    city_name: "Anuradhapura",
                    city_iata_code: "IZM",
                    country_iso_code: "TR",
                    country_name: "Turkey",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 42,
                airport_id: 42,
                terminal: "3",
                scheduled_time: "2024-01-06T14:50:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 42,
                    airport_name: "Kotoka",
                    iata_code: "ACC",
                    gmt: "6",
                    city_name: "Aberdeen",
                    city_iata_code: "ACC",
                    country_iso_code: "GH",
                    country_name: "Ghana",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 75,
                name: "Qatar Airways",
                iata: "QR",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 2,
        flight_id: 1,
        ticket_type: "first",
        ticket_amount: 20,
        fare_amount: "1500000.00",
        valid_until: "2024-01-26T17:00:00.000Z",
        created_at: "2024-01-24T16:04:30.398Z",
        updated_at: null,
        flight: {
            flight_id: 1,
            departure_id: 38,
            arrival_id: 60,
            airline_id: 15,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "6811",
            iata: "AA6811",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 38,
                airport_id: 38,
                terminal: "3",
                scheduled_time: "2024-01-06T09:00:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 38,
                    airport_name: "Dougherty County",
                    iata_code: "ABY",
                    gmt: "-5",
                    city_name: "Albina",
                    city_iata_code: "ABY",
                    country_iso_code: "US",
                    country_name: "United States",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 60,
                airport_id: 60,
                terminal: "1",
                scheduled_time: "2024-01-06T15:05:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 60,
                    airport_name: "Aden International Airport",
                    iata_code: "ADE",
                    gmt: "3",
                    city_name: "Aguaclara",
                    city_iata_code: "ADE",
                    country_iso_code: "YE",
                    country_name: "Yemen",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 15,
                name: "Iberia",
                iata: "IB",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    },
    {
        ticket_id: 1,
        flight_id: 6,
        ticket_type: "first",
        ticket_amount: 20,
        fare_amount: "200000.00",
        valid_until: "2024-01-27T14:14:21.000Z",
        created_at: "2024-01-23T14:14:33.703Z",
        updated_at: null,
        flight: {
            flight_id: 6,
            departure_id: 12,
            arrival_id: 34,
            airline_id: 33,
            transit: 0,
            first_seat: 20,
            business_seat: 120,
            economy_seat: 220,
            flight_status: "scheduled",
            flight_number: "5080",
            iata: "TV5080",
            created_at: "2023-12-09T09:05:20.986Z",
            updated_at: null,
            departure: {
                departure_id: 12,
                airport_id: 12,
                terminal: "8",
                scheduled_time: "2024-01-06T17:00:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 12,
                    airport_name: "Al Ain",
                    iata_code: "AAN",
                    gmt: "4",
                    city_name: "Mala Mala",
                    city_iata_code: "AAN",
                    country_iso_code: "AE",
                    country_name: "United Arab Emirates",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            arrival: {
                arrival_id: 34,
                airport_id: 34,
                terminal: "2",
                scheduled_time: "2024-01-06T09:05:00.000Z",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null,
                airport_details: {
                    airport_id: 34,
                    airport_name: "Al-Aqiq",
                    iata_code: "ABT",
                    gmt: "3",
                    city_name: "Abidjan",
                    city_iata_code: "ABT",
                    country_iso_code: "SA",
                    country_name: "Saudi Arabia",
                    created_at: "2023-12-09T09:05:20.986Z",
                    updated_at: null
                }
            },
            airline: {
                airline_id: 33,
                name: "Air Canada",
                iata: "AC",
                image: "https://res.cloudinary.com/ddpriosuk/image/upload/v1694179155/icon_24hrs_bmttbd.png",
                created_at: "2023-12-09T09:05:20.986Z",
                updated_at: null
            }
        }
    }
  ];